name: Update Events Data

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install axios

      - name: Fetch Contentful data
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ACCESS_TOKEN: ${{ secrets.CONTENT_DELIVERY_API_ACCESS_TOKEN }}
        run: |
          node <<'EOF'
          import fs from 'fs';
          import axios from 'axios';
          
          const url = `https://cdn.contentful.com/spaces/${process.env.SPACE_ID}/environments/master/entries?access_token=${process.env.ACCESS_TOKEN}&content_type=event`;

          const fetchData = async () => {
            try {
              const res = await axios.get(url);
              console.log('📥 Fetched events:', JSON.stringify(res.data.items, null, 2));

              if (!fs.existsSync('src/data')) {
                fs.mkdirSync('src/data', { recursive: true });
              }

              fs.writeFileSync('src/data/events.json', JSON.stringify(res.data, null, 2));
              console.log('✅ events.json updated successfully');
            } catch (err) {
              console.error('❌ Error fetching Contentful data:', err.message);
              process.exit(1);
            }
          };

          fetchData();
          EOF

      - name: Commit and push if changed
        env:
          PAT_PUSH: ${{ secrets.PAT_PUSH }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/data/events.json
          git diff --staged --quiet && exit 0
          git commit -m "Update events.json"
          git push https://x-access-token:${PAT_PUSH}@github.com/${{ github.repository }}.git HEAD:master
